### ISSUE TITLE
What is redis used for?

### ISSUE THREAD

**Issue by figassis** [nodemailer/import-maildir#1]
Does the redis config need to be the same as the wildduck instance or is redis used only as a local store/cache?

**Comment by andris9** [comment]
import-maildir uses wildduck library under the hood that requires Redis. It is supposed to be the same instance as production though nothing breaks if you use another one. When a message is imported then WildDuck fires notifications using Redis to IMAP but most probably the user has not yet signed in, as you are still importing, so there is no-one to catch that signal.

**Comment by figassis** [comment]
Awesome! doing an import, its really fast :-). Last question, are imports idempotent? If I get an error and repeat the process, will I have duplicate messages/folders/etc?

**Comment by figassis** [comment]
nvm, STORESKIP :-)

**Comment by andris9** [comment]
STORESKIP might not be reliable currently as the duplicate detection is kind of broken right now, you have to test how it works out for you.
